//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.nita.saml20.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Saml20Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Saml20Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.nita.saml20.Properties.Saml20Resources", typeof(Saml20Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action SAMLRequest requires you to set the Request property..
        /// </summary>
        internal static string ActionRequestMismatch {
            get {
                return ResourceManager.GetString("ActionRequestMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action SAMLResponse requires you to set the Response property..
        /// </summary>
        internal static string ActionResponseMismatch {
            get {
                return ResourceManager.GetString("ActionResponseMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IDPEndPoint with id &quot;{0}&quot; was not found in configuration file..
        /// </summary>
        internal static string InvalidIdpEndPointId {
            get {
                return ResourceManager.GetString("InvalidIdpEndPointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;IDPEndPoints&gt; element under &lt;Safewhere.SAML20Federation&gt; in configuration file..
        /// </summary>
        internal static string MissingIDPEndpoints {
            get {
                return ResourceManager.GetString("MissingIDPEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata not found for idpEndpoint with id {0}.
        /// </summary>
        internal static string MissingMetadata {
            get {
                return ResourceManager.GetString("MissingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;metadata&quot; attribute on the &lt;IDPEndPoints&gt; tag must contain the path to a directory holding metadata descriptions of your federation partners..
        /// </summary>
        internal static string MissingMetadataLocation {
            get {
                return ResourceManager.GetString("MissingMetadataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;Safewhere.SAML20Federation&gt; element in configuration file..
        /// </summary>
        internal static string MissingSaml20Federation {
            get {
                return ResourceManager.GetString("MissingSaml20Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;ServiceProvider&gt; element under &lt;Safewhere.SAML20Federation&gt; element in configuration file..
        /// </summary>
        internal static string MissingServiceProvider {
            get {
                return ResourceManager.GetString("MissingServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing id attribute on the &lt;ServiceProvider&gt; element in configuration file..
        /// </summary>
        internal static string MissingServiceProviderId {
            get {
                return ResourceManager.GetString("MissingServiceProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;SigningCertificate&gt; element under &lt;ServiceProvider&gt; element in configuration file..
        /// </summary>
        internal static string MissingSigningCertificate {
            get {
                return ResourceManager.GetString("MissingSigningCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;SLO&gt; element or missing attribute under &lt;IDPEndPoints&gt; in configuration file..
        /// </summary>
        internal static string MissingSLO {
            get {
                return ResourceManager.GetString("MissingSLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &lt;SSO&gt; element or missing attribute under &lt;IDPEndPoints&gt; in configuration file..
        /// </summary>
        internal static string MissingSSO {
            get {
                return ResourceManager.GetString("MissingSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the certificate specified in &lt;SigningCertificate&gt; element in configuration file..
        /// </summary>
        internal static string SigningCertficateLoadError {
            get {
                return ResourceManager.GetString("SigningCertficateLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing access to private key for signing certificate..
        /// </summary>
        internal static string SigningCertificateMissingPrivateKey {
            get {
                return ResourceManager.GetString("SigningCertificateMissingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of request (&quot;{0}&quot;) is not supported..
        /// </summary>
        internal static string UnsupportedRequestType {
            get {
                return ResourceManager.GetString("UnsupportedRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of response (&quot;{0}&quot;) is not supported..
        /// </summary>
        internal static string UnsupportedResponseType {
            get {
                return ResourceManager.GetString("UnsupportedResponseType", resourceCulture);
            }
        }
    }
}
